### ISSUE TITLE
Error with reddit client id.

### ISSUE THREAD

**Issue by Claesse1337** [Adam-Jimenez/auddit#16]
When running the reddit scrape test, I get an error that the client id is invalid. Does it take a certain amount of time for the client_id to get active or is something wrong? I have not written it wrong nor have I done any further changes in the script.

**Comment by aggin23** [comment]
I have the same problem. What's the solution?

**Comment by alphanumericaltycoon** [comment]
1. Double check your client id and client secret code from reddit.
2. Set the system variables

You can set your system environmental variable by writing in the terminal the following commands:

$export REDDIT_CLIENT_ID=YOURCODEFROMREDDITHERE
$export REDDIT_CLIENT_SECRET=YOURCODEFROMREDDITHERE

This will set the variables which you can then confirm by using the command
echo $REDDIT_CLIENT_ID 
(this will return the code string that you entered)

echo $REDDIT_CLIENT_SECRET
(this will return the code string that you entered)
