### ISSUE TITLE
Generate_Video...Killed

### ISSUE THREAD

**Issue by Claesse1337** [Adam-Jimenez/auddit#17]
Everything is going smooth, but then it starts the generate_video task, and after a few seconds it says Killed. The script is then interrupted. No error output or anything?

**Comment by Adam-Jimenez** [comment]
Interesting! I never saw this before, but it could be useful if you could use a debugger and let me know exactly on which line it dies.

**Comment by Claesse1337** [comment]
Im running it on a virtualmachine so that could have been why, It ran out of memory. Fixed it by increasing ram, how ever now Im getting stuck at uploading video. It comes to upload_video task, but never finishes just sits there. Not sure whats wrong. Can it be the youtube uploader is not installed properly?

**Comment by Adam-Jimenez** [comment]
the youtube uploader is a standalone binary, there shouldn't be anything to install. Normally it spawns a browser for the oauth2 login and then it uploads to your channel, if everything was configured properly. Does your VM have internet access?

You can try a manual upload with the parameters described here: https://github.com/porjo/youtubeuploader .
The binary is in the bin folder.
