### ISSUE TITLE
Client ID Error

### ISSUE THREAD

**Issue by aggin23** [Adam-Jimenez/auddit#19]
Traceback (most recent call last):
  File "C:/Users/Meridius/Desktop/auddit-master (1)/auddit-master/src/main.py", line 1, in <module>
    from tasks.scrape_reddit.task import get_hottest_post
  File "C:\Users\Meridius\Desktop\auddit-master (1)\auddit-master\src\tasks\scrape_reddit\task.py", line 6, in <module>
    client_id = os.environ["MYKEYHERE"]
  File "C:\Users\Meridius\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'MYKEYHERE'

**Comment by Zuccy** [comment]
@aggin23 I'm also having this error, were you able to fix it?

**Comment by aggin23** [comment]
EDIT: WRONG Thread. I don' really remember what I did, but yeah I fixed every error.
I think you need to add the Reddit key to your system environment variable.

**Comment by alphanumericaltycoon** [comment]
Just for everyone's benefit - you can set your system environmental variable by writing in the terminal the following commands:

$export REDDIT_CLIENT_ID=YOURCODEFROMREDDITHERE
$export REDDIT_CLIENT_SECRET=YOURCODEFROMREDDITHERE

This will set the variables which you can then confirm by using the command
echo $REDDIT_CLIENT_ID 
(this will return the code string that you entered)

echo $REDDIT_CLIENT_SECRET
(this will return the code string that you entered)

I'm new to Linux but from what I gathered you need to do this every time you open a terminal window in order for the script to work.
